### ISSUE TITLE
AuthToken is not set when sending it to the constructor

### ISSUE THREAD

**Issue by wilhelmf-devel** [CertCenter/phpCertCenter#1]
When giving the AuthToken to the constructor when creating an object of this class the Token is not set.
This is a minor bug in line 52 of this version. 

It should be 
`$this->setAuthorization($AuthorizationToken);`
instead if
`$this->setAuthorization=$AuthorizationToken;`

**Comment by amallek** [comment]
Thanks for the report. Has been fixed.
